### PR TITLE
feat: improve user menu

### PR DESCRIPTION
**Pull request by rohan-chaturvedi**
## :mag: Overview

Misc improvements to the user menu for easier navigation to common settings and info

## :bulb: Proposed Changes

* Add details of currently logged in user to menu
* Add dark mode toggle to menu
* Add link to settings + restyled sign out button to menu
* Added a fallback to the `Avatar` component for when user avatar path is unavailable
* Add separate "App" tab in settings for app-related settings

### User menu

Screenshot from 2024-05-28 21-03-02

Screenshot from 2024-05-28 21-03-12

### New App settings tab

Screenshot from 2024-05-28 21-05-35

## :memo: Release Notes

* Restyled the user menu provide more information and quick access to common settings
* Moved app-related settings to Settings -> App
* Added a fallback for user avatar when the image is unavailable

### :green_heart: Did You...

- [x] Ensure linting passes (code style checks)?
~~- [ ] Update dependencies and lockfiles (if required)~~
- [x] Verify the app builds locally?
- [x] Manually test the changes on different browsers/devices?

### CODE REVIEW

**Comment by nimish-ks** [comment]
@rohan-chaturvedi 

redundant theme switchers on the choose a workspace screen:
image


the theme switcher appears in a few different places in settings (account and app):
image

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi
> 
> redundant theme switchers on the choose a workspace screen: image
> 
> the theme switcher appears in a few different places in settings (account and app): image

Fixed

**Comment by nimish-ks** [comment]
poor visibility labels and icons on the light theme in the choose a workspace screen:
image

the app tab doesn't show up for users with `dev` level access:
image

**Comment by rohan-chaturvedi** [comment]
> poor visibility labels and icons on the light theme in the choose a workspace screen: image
> 
> the app tab doesn't show up for users with `dev` level access: image

@nimish-ks Fixed!

**Review by nimish-ks — APPROVED** [review]

**Pull request merged**
