### PR TITLE
feat: validate private api encrypted data format

### PR DESCRIPTION
**Pull request by rohan-chaturvedi**
## :mag: Overview

The E2E encrypted secrets api accepts secrets that are encrypted client-side (by the CLI or SDKs), but there is currently no validation to ensure that the format of the encrypted data matches the phase ciphertext format. 

## :bulb: Proposed Changes

Add a validation check for encrypted fields sent via `POST` and `PUT` requests to make sure they are encrypted and formatted correctly. Return a `400 Bad request` error if they are malformed. 

## :memo: Release Notes

Added validation to ensure malformed or unencrypted data cannot be saved via the E2E encrypted secrets API.

### :green_heart: Did You...

- [x] Ensure linting passes (code style checks)?
~~- [ ] Update dependencies and lockfiles (if required)~~
- [x] Verify the app builds locally?
- [x] Manually test the changes on different browsers/devices?

### CODE REVIEW

**Comment by nimish-ks** [comment]
@rohan-chaturvedi when i try to create secrets from the cli:

```
Exception: 🗿 Request failed with status code 400: Invalid ciphertext format
```

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi when i try to create secrets from the cli:
> 
> ```
> Exception: 🗿 Request failed with status code 400: Invalid ciphertext format
> ```

Should be fixed now @nimish-ks

**Review by nimish-ks — APPROVED** [review]

**Comment by nimish-ks** [comment]
chore: remove re import if you are not using regex

**Comment by rohan-chaturvedi** [comment]
> chore: remove re import if you are not using regex

I am

**Pull request merged**
