### PR TITLE
fix: overlapping password icons | Edge Browser

### PR DESCRIPTION
**Pull request by amitsgh**
# Description 📣

This pull request addresses and resolves the issue of overlapping password icons (#102) specifically observed in the Edge browser. The issue was causing icons appearing on top of each other, leading to a poor user experience.

## Type ✨

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

- [x] Checked all possible password inputs icons.
- [x]  Ensured that the password reveal control is appropriately hidden/revealed
- [x] Checked password inputs with special attention to the Edge
- [ ] Checked password inputs for other browsers

### CODE REVIEW

**Review by rohan-chaturvedi — APPROVED** [review]

**Comment by rohan-chaturvedi** [comment]
Thanks for the fix, @amitsgh!

@nimish-ks Could you take a look at the build issue? Seems to be a dockerhub authentication problem.

**Comment by nimish-ks** [comment]
@rohan-chaturvedi its because the PR is opened by a non-member of this repo.. GitHub actions doesn't release credentials during a pipeline.

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi its because the PR is opened by a non-member of this repo.. GitHub actions doesn't release credentials during a pipeline.

Yeah but I closed and re-opened it, shouldn't that fix it?

**Comment by nimish-ks** [comment]
> > @rohan-chaturvedi its because the PR is opened by a non-member of this repo.. GitHub actions doesn't release credentials during a pipeline.
> 
> Yeah but I closed and re-opened it, shouldn't that fix it?

Don't think it does in this case.

**Comment by nimish-ks** [comment]
> > @rohan-chaturvedi its because the PR is opened by a non-member of this repo.. GitHub actions doesn't release credentials during a pipeline.
> 
> Yeah but I closed and re-opened it, shouldn't that fix it?

You can create an in between branch and merge this PR, which will trigger a build.

**Pull request merged**
